# Generated by Django 4.2.2 on 2023-09-17 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0003_rename_id_instrument_type_instrumentsmodels_instrument_type_and_more'),
        ('main', '0005_customers_main_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Aberto', 'Open'), ('Aguardando pagamento', 'Await Payment'), ('Pagamento realizado', 'Made Payment'), ('Cancelado', 'Canceled')], default='Aberto', max_length=20)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacts_customers')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers_main')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de crédito', 'Cartao De Credito'), ('Boleto bancário', 'Boleto'), ('Pix', 'Pix')], max_length=250)),
                ('modo_pagamento', models.CharField(choices=[('À vista', 'Avista'), ('Parcelado', 'Parcelado')], max_length=250)),
                ('prazo_entrega', models.DateTimeField()),
                ('validade_proposta', models.DateTimeField()),
                ('frete', models.CharField(max_length=250)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_orcamento', models.CharField(choices=[('Instalação', 'Instalacao'), ('Manutenção', 'Manutencao'), ('Venda', 'Venda')], max_length=250)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_unitario', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('acrescimo', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('desconto', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('garantia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao')], max_length=250)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentsinstruments')),
            ],
        ),
    ]
