# Generated by Django 4.2.2 on 2024-01-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_tipoorcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_solicitacao', models.CharField(max_length=250)),
            ],
        ),
    ]
