# Generated by Django 4.2.2 on 2024-01-25 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_customers_main_corporate_name'),
        ('orcamento', '0003_pagamentocondicao_pagamentoforma_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contacts_customers'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customers_main'),
        ),
    ]
