# Generated by Django 4.2.2 on 2024-01-25 21:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_alter_instrumenttypes_condicoes_ambientais_pre_and_more'),
        ('orcamento', '0005_alter_orcamentopayment_prazo_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='acrescimo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='desconto',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='garantia',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Nao')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentsinstruments'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo_orcamento',
            field=models.CharField(blank=True, choices=[('Instalação', 'Instalacao'), ('Manutenção', 'Manutencao'), ('Venda', 'Venda')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='valor_unitario',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orcamentopayment',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('Cartão de crédito', 'Cartao De Credito'), ('Boleto bancário', 'Boleto'), ('Pix', 'Pix')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentopayment',
            name='frete',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentopayment',
            name='modo_pagamento',
            field=models.CharField(blank=True, choices=[('À vista', 'Avista'), ('Parcelado', 'Parcelado')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentopayment',
            name='orcamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento'),
        ),
    ]
