# Generated by Django 4.2.2 on 2024-02-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemS', '0010_remove_ordemdeservico_equipamento'),
        ('orcamento', '0006_alter_equipamento_acrescimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexosOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
                ('area_acreditacao', models.CharField(blank=True, max_length=250, null=True)),
                ('especificacao', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_calibracao', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_item', models.CharField(blank=True, max_length=250, null=True)),
                ('local', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pontos', models.TextField(blank=True, null=True)),
                ('pontos_valor_adicional', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoEnsaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
                ('area_acreditacao', models.CharField(blank=True, max_length=250, null=True)),
                ('especificacao', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_servico', models.CharField(blank=True, max_length=250, null=True)),
                ('local', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
                ('area_acreditacao', models.CharField(blank=True, max_length=250, null=True)),
                ('especificacao', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_servico', models.CharField(blank=True, max_length=250, null=True)),
                ('local', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoQT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
                ('area_acreditacao', models.CharField(blank=True, max_length=250, null=True)),
                ('especificacao', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_servico', models.CharField(blank=True, max_length=250, null=True)),
                ('local', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicosOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamentopayment',
            name='orcamento',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='forma_solicitacao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_orcamento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='validade_proposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='OrcamentoPayment',
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento'),
        ),
        migrations.AddField(
            model_name='anexosorcamento',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento'),
        ),
    ]
