# Generated by Django 4.2.2 on 2024-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0008_alter_orcamento_validade_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade_proposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
