# Generated by Django 4.2.2 on 2024-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_alter_orcamento_validade_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='contrato',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='local',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
