# Generated by Django 4.2.2 on 2024-02-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0010_orcamento_contrato_orcamento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
