# Generated by Django 4.2.2 on 2024-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0011_alter_orcamento_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexosorcamento',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos_orcamentos/'),
        ),
    ]
