# Generated by Django 4.2.2 on 2024-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0012_alter_anexosorcamento_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicosorcamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='area_acreditacao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='especificacao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='local',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='pontos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='pontos_valor_adicional',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='tipo_calibracao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='tipo_item',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='tipo_servico',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicosorcamento',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
