# Generated by Django 4.2.2 on 2024-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0013_remove_servicosorcamento_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='contato',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
