# Generated by Django 4.2.2 on 2024-02-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_anexoscliente'),
        ('orcamento', '0014_alter_orcamento_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contacts_customers'),
        ),
    ]
