# Generated by Django 4.2.2 on 2024-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0015_alter_orcamento_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicocalibracao',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicocalibracao',
            name='pontos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicocalibracao',
            name='pontos_valor_adicional',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicocalibracao',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicoensaio',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicoensaio',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicomanutencao',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicomanutencao',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicoqt',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicoqt',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicosorcamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicosorcamento',
            name='pontos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicosorcamento',
            name='pontos_valor_adicional',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicosorcamento',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
