# Generated by Django 4.2.2 on 2024-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0017_alter_servicocalibracao_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='acrescimo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='desconto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_de_desconto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
