# Generated by Django 4.2.2 on 2024-03-08 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_fornecedores_id_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamento', '0018_orcamento_acrescimo_orcamento_desconto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('validade_proposta', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=250, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=250, null=True)),
                ('local', models.CharField(blank=True, max_length=250, null=True)),
                ('contrato', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_de_desconto', models.CharField(blank=True, max_length=250, null=True)),
                ('desconto', models.CharField(blank=True, max_length=250, null=True)),
                ('acrescimo', models.CharField(blank=True, max_length=250, null=True)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_orcamento', models.CharField(blank=True, max_length=250, null=True)),
                ('forma_solicitacao', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Aberto', 'Open'), ('Aguardando pagamento', 'Await Payment'), ('Pagamento realizado', 'Made Payment'), ('Cancelado', 'Canceled')], default='Aberto', max_length=20)),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contacts_customers')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_orcamento_set', to=settings.AUTH_USER_MODEL)),
                ('responsavel_atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_atividade_set', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customers_main')),
            ],
        ),
        migrations.CreateModel(
            name='ServicosOrcamentoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
                ('area_acreditacao', models.CharField(blank=True, max_length=250, null=True)),
                ('especificacao', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_servico', models.CharField(blank=True, max_length=250, null=True)),
                ('local', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('valor', models.CharField(blank=True, max_length=250, null=True)),
                ('pontos', models.CharField(blank=True, max_length=250, null=True)),
                ('pontos_valor_adicional', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_calibracao', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_item', models.CharField(blank=True, max_length=250, null=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamentoatividade')),
            ],
        ),
        migrations.CreateModel(
            name='AnexosOrcamentoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos_orcamentos/')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamentoatividade')),
            ],
        ),
    ]
