# Generated by Django 4.2.2 on 2024-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0019_orcamentoatividade_servicosorcamentoatividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoatividade',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
