# Generated by Django 4.2.2 on 2024-03-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0020_alter_orcamentoatividade_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
