# Generated by Django 4.2.2 on 2024-03-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0021_alter_orcamento_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='orcamento_raiz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(default='Aberto', max_length=20),
        ),
    ]
