# Generated by Django 4.2.2 on 2024-03-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0022_orcamento_orcamento_raiz_alter_orcamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='orcamento_raiz',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
