# Generated by Django 4.2.2 on 2023-09-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customers_main_tipo_cliente'),
        ('instruments', '0003_rename_id_instrument_type_instrumentsmodels_instrument_type_and_more'),
        ('padrao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faixas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('amplitude_max', models.IntegerField(blank=True, null=True)),
                ('amplitude_min', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Padrão',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novo_Padrão',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=50)),
                ('setor_cliente', models.CharField(max_length=50)),
                ('prox_calibracao', models.DateField(blank=True)),
                ('prox_verificacao', models.DateField(blank=True)),
                ('calibrar_a_cada', models.CharField(blank=True, max_length=50)),
                ('verificar_a_cada', models.CharField(blank=True, max_length=50)),
                ('padrao_status', models.BooleanField(default=True)),
                ('utilizado_campo', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('calibrar_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.tipo_padrão')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers_main')),
                ('faixas', models.ManyToManyField(to='padrao.faixas')),
                ('modelo_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentsmodels')),
                ('tipo_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumenttypes')),
            ],
        ),
        migrations.AddField(
            model_name='faixas',
            name='resolucao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.resolucao'),
        ),
        migrations.AddField(
            model_name='faixas',
            name='unidade_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.unidade_medida'),
        ),
    ]
