# Generated by Django 4.2.2 on 2023-09-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padrao', '0002_faixas_resolucao_tipo_padrão_novo_padrão_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio_Aceitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('formula_de_validacao', models.CharField(choices=[('erro', 'Erro'), ('erro + incert', 'Erro + Incerteza'), ('incerteza', 'Incerteza'), ('percent', 'Percentual do ponto lido')], max_length=50)),
                ('amplitude_max', models.IntegerField(blank=True, null=True)),
                ('amplitude_min', models.IntegerField(blank=True, null=True)),
                ('limite_max', models.IntegerField(blank=True, null=True)),
                ('limite_min', models.IntegerField(blank=True, null=True)),
                ('grandeza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.grandeza')),
                ('padrao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.novo_padrão')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.unidade_medida')),
            ],
        ),
    ]
