# Generated by Django 4.2.2 on 2023-09-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimentos', '0001_initial'),
        ('comercial', '0002_areaacreditacao'),
        ('main', '0004_alter_customers_main_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentsBands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instrument', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('id_measurement', models.FloatField(blank=True, null=True)),
                ('row_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instruments_bands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('id_instrument_type', models.IntegerField(blank=True, null=True)),
                ('removed', models.IntegerField(blank=True, null=True)),
                ('expressions', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('identifier', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('faixas_padronizadas', models.BooleanField(default=False)),
                ('condicoes_ambientais_temp', models.BooleanField(default=False)),
                ('condicoes_ambientais_umi', models.BooleanField(default=False)),
                ('condicoes_ambientais_pre', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('area_acreditaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.areaacreditacao')),
                ('procedimento', models.ManyToManyField(blank=True, to='procedimentos.dados_procedimento')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.setor')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentsInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.CharField(blank=True, max_length=250, null=True)),
                ('calibration_frequency_months', models.CharField(blank=True, max_length=250, null=True)),
                ('next_calibration', models.DateField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_current_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customersectors')),
                ('id_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customers_main')),
                ('id_instrument_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentsmodels')),
                ('id_instrument_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumenttypes')),
                ('id_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.suppliers')),
            ],
        ),
    ]
