# Generated by Django 4.2.2 on 2023-09-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentsmodels',
            name='expressions',
        ),
        migrations.RemoveField(
            model_name='instrumentsmodels',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='instrumentsmodels',
            name='removed',
        ),
        migrations.AlterField(
            model_name='instrumentsmodels',
            name='id_instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumenttypes'),
        ),
    ]
