# Generated by Django 4.2.2 on 2023-11-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_alter_instrumenttypes_condicoes_ambientais_pre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttypes',
            name='condicoes_ambientais_pre',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='instrumenttypes',
            name='condicoes_ambientais_temp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='instrumenttypes',
            name='condicoes_ambientais_umi',
            field=models.CharField(max_length=5),
        ),
    ]
