# Generated by Django 4.2.2 on 2023-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_instrumenttypes_condicoes_ambientais_pre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttypes',
            name='condicoes_ambientais_pre',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='instrumenttypes',
            name='condicoes_ambientais_temp',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='instrumenttypes',
            name='condicoes_ambientais_umi',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
