# Generated by Django 4.2.2 on 2024-01-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_anexo_customuser_anexo_customuser_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='anexo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='anexos',
            field=models.ManyToManyField(blank=True, to='accounts.anexo'),
        ),
    ]
