# Generated by Django 4.2 on 2023-05-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('setor', models.CharField(max_length=255)),
                ('ramal', models.CharField(max_length=10)),
                ('telefone_comercial', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('data_nasc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('corporate_name', models.CharField(blank=True, max_length=250, null=True)),
                ('municipal_registration', models.CharField(blank=True, max_length=250, null=True)),
                ('state_registration', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('uf', models.CharField(blank=True, max_length=250, null=True)),
                ('cep', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=250, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_fundation', models.CharField(blank=True, max_length=12, null=True)),
                ('web_site', models.CharField(blank=True, max_length=250, null=True)),
                ('id_market_segment', models.CharField(blank=True, max_length=250, null=True)),
                ('id_size', models.CharField(blank=True, max_length=250, null=True)),
                ('address_number', models.CharField(blank=True, max_length=250, null=True)),
                ('address_complement', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_day', models.CharField(blank=True, max_length=15, null=True)),
                ('is_requestor_in_field', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_venc', models.CharField(blank=True, max_length=15, null=True)),
                ('company_responsible', models.CharField(blank=True, max_length=250, null=True)),
                ('credit_or_debit_card', models.CharField(blank=True, choices=[('CR', 'Crédito'), ('DB', 'Débito')], default='CR', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_customer', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('acronym', models.TextField(blank=True, null=True)),
                ('phone', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('cnpj', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('web_site', models.TextField(blank=True, null=True)),
                ('corporate_name', models.TextField(blank=True, null=True)),
                ('municipal_registration', models.TextField(blank=True, null=True)),
                ('state_registration', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_city', models.FloatField(blank=True, null=True)),
                ('id_neighborhood', models.FloatField(blank=True, null=True)),
                ('id_state', models.FloatField(blank=True, null=True)),
                ('cep', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_laboratory', models.IntegerField(blank=True, null=True)),
                ('is_manufacturer', models.IntegerField(blank=True, null=True)),
                ('removed', models.IntegerField(blank=True, null=True)),
                ('date_of_fundation', models.TextField(blank=True, null=True)),
                ('is_carrier', models.FloatField(blank=True, null=True)),
                ('agency', models.FloatField(blank=True, null=True)),
                ('account_number', models.FloatField(blank=True, null=True)),
                ('id_bank', models.FloatField(blank=True, null=True)),
                ('is_abstract_person', models.IntegerField(blank=True, null=True)),
                ('stock_expression', models.FloatField(blank=True, null=True)),
                ('address_number', models.TextField(blank=True, null=True)),
                ('address_complement', models.TextField(blank=True, null=True)),
                ('is_approved', models.FloatField(blank=True, null=True)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('id_evaluation_status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('sector', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('commercial_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('cellular', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', models.CharField(blank=True, max_length=250, null=True)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers_main')),
            ],
        ),
    ]
