# Generated by Django 4.2 on 2023-06-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contacts_customers_cellular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts_customers',
            name='cellular',
            field=models.CharField(blank=True, default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts_customers',
            name='commercial_phone',
            field=models.CharField(blank=True, default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts_customers',
            name='description',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
