# Generated by Django 4.2 on 2023-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contacts_customers_cellular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_main',
            name='address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='address_complement',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='address_number',
            field=models.CharField(default=10, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='cep',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='city',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='cnpj',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='corporate_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='neighborhood',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='uf',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
