# Generated by Django 4.2.2 on 2023-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customers_main_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_main',
            name='tipo_cliente',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fabricante', 'Fabricante'), ('cliente/fabricante', 'Cliente/Fabricante')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
