# Generated by Django 4.2.2 on 2024-01-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contacts_customers_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_main',
            name='cpf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='cnpj',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
