# Generated by Django 4.2.2 on 2024-01-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customers_main_cpf_alter_customers_main_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_main',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
