# Generated by Django 4.2.2 on 2024-02-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customers_main_corporate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos_clientes/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customers_main')),
            ],
        ),
    ]
