# Generated by Django 4.2.2 on 2024-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_anexoscliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('cnpj', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('web_site', models.TextField(blank=True, null=True)),
                ('corporate_name', models.TextField(blank=True, null=True)),
                ('municipal_registration', models.TextField(blank=True, null=True)),
                ('state_registration', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_city', models.FloatField(blank=True, null=True)),
                ('id_neighborhood', models.FloatField(blank=True, null=True)),
                ('id_state', models.FloatField(blank=True, null=True)),
                ('cep', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_laboratory', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
