# Generated by Django 4.2.2 on 2024-03-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fornecedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedores',
            name='id_city',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='id_neighborhood',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='id_state',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='is_laboratory',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='address_complement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='address_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='company_responsible',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='cpf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='credibilidade',
            field=models.CharField(blank=True, choices=[('satisfatorio', 'Satisfatório'), ('insatisfatorio', 'Insatisfatório')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='credit_or_debit_card',
            field=models.CharField(blank=True, choices=[('CR', 'Crédito'), ('DB', 'Débito')], default='CR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='custo_beneficio',
            field=models.CharField(blank=True, choices=[('satisfatorio', 'Satisfatório'), ('insatisfatorio', 'Insatisfatório')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='data_retorna_rapidamente',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='data_soluciona_problemas',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='date_of_fundation',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='desempenha_qualidade',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fornecedor_acreditado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('n/a', 'N/A')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fornecedor_cnpj_ativo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('n/a', 'N/A')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='id_market_segment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='id_size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='is_requestor_in_field',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='payment_day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='payment_venc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='produto_fornecidos',
            field=models.CharField(blank=True, choices=[('calibracao', 'Calibração'), ('produto', 'Produto'), ('material_de_referencia', 'Material de Referência'), ('PEP', 'PEP'), ('certificador', 'Certificador'), ('outros', 'Outros')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='retorna_rapidamente',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='soluciona_problemas',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='tipo_cliente',
            field=models.CharField(choices=[('fabricante', 'Fabricante'), ('cliente/fabricante', 'Cliente/Fabricante')], default='fabricante', max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='uf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='cep',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='tipo_cliente',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('cliente/fabricante', 'Cliente/Fabricante')], default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='customers_main',
            name='uf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='cep',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='fax',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='state_registration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='web_site',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='AnexosFornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos_fornecedores/')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fornecedores')),
            ],
        ),
    ]
