# Generated by Django 4.2.2 on 2023-09-05 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=6)),
                ('setor_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_atividade', models.DurationField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('temperatura', models.TextField(blank=True, null=True)),
                ('umidade', models.TextField(blank=True, null=True)),
                ('pressao', models.TextField(blank=True, null=True)),
                ('fa_registro', models.BooleanField(default=True)),
                ('utilizado_fluxo', models.BooleanField(default=True)),
                ('bloquear_certificado_ko', models.BooleanField(default=False)),
                ('estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.estoque')),
            ],
        ),
    ]
