# Generated by Django 4.2 on 2023-05-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
