# Generated by Django 4.2 on 2023-07-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemS', '0002_dados_arquivo_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='contato',
        ),
    ]
