# Generated by Django 4.2 on 2023-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemS', '0004_dados_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='open', max_length=20),
        ),
    ]
