# Generated by Django 4.2 on 2023-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemS', '0006_dados_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='setor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
