# Generated by Django 4.2.2 on 2023-10-01 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
        ('ordemS', '0008_alter_dados_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=100)),
                ('nota_fiscal', models.CharField(max_length=100)),
                ('tipo_envio', models.CharField(max_length=100)),
                ('embalagem', models.CharField(max_length=100)),
                ('data_chamado', models.DateField()),
                ('data_atendimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('saida_prevista', models.DateField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='media/')),
                ('setor', models.CharField(choices=[('Recebimento', 'Recebimento'), ('Expedição', 'Expedição'), ('Faturamento', 'Faturamento'), ('Comercial', 'Comercial'), ('Laboratório Interno', 'Laboratório Interno'), ('Financeiro', 'Financeiro'), ('Pendencias Laboratorio', 'Pendencias Laboratorio'), ('Pendencias Comercial', 'Pendencias Comercial'), ('OS para Manutenção', 'OS para Manutenção'), ('Manutenção a Executar', 'Manutenção a Executar'), ('OSs MANUTENÇÃO FINALIZADAS', 'OSs MANUTENÇÃO FINALIZADAS'), ('Qualificação Térmica', 'Qualificação Térmica'), ('Treinamento', 'Treinamento'), ('Ordem de Contrato', 'Ordem de Contrato'), ('NENHUM', 'NENHUM'), ('OS contrato Finalizada', 'OS contrato Finalizada'), ('Pendência de Faturamento', 'Pendência de Faturamento'), ('Manutenção IHENE', 'Manutenção IHENE'), ('Laboratorio Externo', 'Laboratorio Externo'), ('Avaliação de Manutenção', 'Avaliação de Manutenção'), ('Pendências de Peças Manutenção', 'Pendências de Peças Manutenção'), ('Pendências de Manutenção', 'Pendências de Manutenção'), ('Equipamento Garantia', 'Equipamento Garantia'), ('HYT', 'HYT'), ('Qualidade', 'Qualidade'), ('Marketing', 'Marketing'), ('IMAGEM', 'IMAGEM')], default='', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='open', max_length=20)),
                ('info_instrumentos', models.TextField()),
                ('observacoes', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.equipamento')),
            ],
        ),
    ]
