# Generated by Django 4.2.2 on 2024-02-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemS', '0009_ordemdeservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='equipamento',
        ),
    ]
