# Generated by Django 4.2.2 on 2023-09-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0003_rename_id_instrument_type_instrumentsmodels_instrument_type_and_more'),
        ('main', '0005_customers_main_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento_eletronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_procedimento', models.CharField(choices=[('calibracao', 'Calibração'), ('ensaio', 'Ensaio')], max_length=11)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('tipo_calibracao', models.CharField(choices=[('todos', 'Todos'), ('ensaio elétrico', 'Ensaio Elétrico'), ('rastreado', 'Rastreado'), ('rbc', 'RBC')], max_length=20)),
                ('local', models.CharField(choices=[('todos', 'Todos'), ('laboratorio', 'Laboratório'), ('campo', 'Campo (in-company)')], max_length=20)),
                ('ult_analise_critica', models.DateField(blank=True)),
                ('periodo_revisao', models.IntegerField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers_main')),
                ('tipo_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumenttypes')),
            ],
        ),
    ]
