# Generated by Django 4.2.2 on 2023-09-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procEletronicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresCalculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.TextField(blank=True, null=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procEletronicos.procedimento_eletronico')),
            ],
        ),
    ]
